### ISSUE TITLE
KeyError: "['ip_flags' 'tcp_flags' 'mqtt_flags'] not found in axis"

### ISSUE THREAD

**Issue by GenjiM1n4moto** [AbertayMachineLearningGroup/MQTT_ML#1]
After downloading the code and the dataset, I ran the command 
`python classification.py --mode 0 --output ./result --verbose true`
 an error occured.
The detailed output was

Starting Slice #: 0
Start Classification
classification.py:278: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30) have mixed types.Specify dtype option on import or set low_memory=False.
  x, y = load_file(prefix + 'normal.csv',
Traceback (most recent call last):
  File "classification.py", line 278, in <module>
    x, y = load_file(prefix + 'normal.csv', 
  File "classification.py", line 86, in load_file
    dataset.drop(columns=columns_to_drop_packet, inplace = True)
  File "/home/user/anaconda3/envs/IDS/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/IDS/lib/python3.8/site-packages/pandas/core/frame.py", line 4906, in drop
    return super().drop(
  File "/home/user/anaconda3/envs/IDS/lib/python3.8/site-packages/pandas/core/generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/user/anaconda3/envs/IDS/lib/python3.8/site-packages/pandas/core/generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/user/anaconda3/envs/IDS/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['ip_flags' 'tcp_flags' 'mqtt_flags'] not found in axis"

**Comment by HananHindy** [comment]
Fixed. Thank you for pointing this out!

**Comment by monarchinc** [comment]
I have been getting this same error how can I rectify this?

**Comment by HananHindy** [comment]
Get the latest version of the code. It should be fixed.
